backend:
  build:
    context: ./backend
    dockerfile: Dockerfile
  expose:
    - "80"
  environment:
    - DATABASE_URL=sqlite:///./storage/metabench.db

frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
  expose:
    - "80"
  environment:
    - VITE_API_URL=http://fqzefh8alsmicovnxdo36zre.83.212.96.37.sslip.io
  depends_on:
    - backend
# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     environment:
#       - DATABASE_URL=sqlite:///./metabench.db
#     volumes:
#       - ./backend:/app
#       - backend-data:/app/data

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173"
#     environment:
#       - VITE_API_URL=http://localhost:8000
#     volumes:
#       - ./frontend/src:/app/src
#     depends_on:
#       - backend
  # Optional: PostgreSQL for production
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: metabench
  #     POSTGRES_USER: metabench
  #     POSTGRES_PASSWORD: metabench_secret
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  backend-data: # pgdata:
