"""
Seed data for BenchIndex – 50 top LLMs with real benchmark scores.
Sources: Chatbot Arena, ArtificialAnalysis, HuggingFace LLB v2, LiveBench, EQBench, OpenRouter.
Scores are real values gathered from public benchmarks as of early 2025.
"""

from sqlalchemy.orm import Session
from models import Model, Benchmark, BenchmarkScore
from normalization import (
    normalize_score,
    compute_weighted_overall_score,
    DEFAULT_WEIGHTS,
)


BENCHMARKS = [
    {
        "name": "MMLU",
        "category": "knowledge",
        "description": "Massive Multitask Language Understanding – 57 subjects",
        "max_score": 100.0,
        "weight": 1.2,
        "source": "Hendrycks et al.",
    },
    {
        "name": "MMLU-Pro",
        "category": "knowledge",
        "description": "MMLU Professional – harder, more discriminative version",
        "max_score": 100.0,
        "weight": 1.3,
        "source": "TIGER-Lab",
    },
    {
        "name": "GPQA Diamond",
        "category": "knowledge",
        "description": "Graduate-level science QA – PhD-level Q&A",
        "max_score": 100.0,
        "weight": 1.3,
        "source": "NYU",
    },
    {
        "name": "GSM8K",
        "category": "math",
        "description": "Grade School Math – multi-step math problems",
        "max_score": 100.0,
        "weight": 1.0,
        "source": "OpenAI",
    },
    {
        "name": "MATH-500",
        "category": "math",
        "description": "Competition-level math – 500 problems",
        "max_score": 100.0,
        "weight": 1.2,
        "source": "Hendrycks et al.",
    },
    {
        "name": "HumanEval",
        "category": "coding",
        "description": "Python coding – functional correctness",
        "max_score": 100.0,
        "weight": 1.2,
        "source": "OpenAI",
    },
    {
        "name": "LiveCodeBench",
        "category": "coding",
        "description": "Live competitive programming benchmark",
        "max_score": 100.0,
        "weight": 1.1,
        "source": "LiveCodeBench",
    },
    {
        "name": "BigBench-Hard",
        "category": "reasoning",
        "description": "23 challenging BIG-Bench reasoning tasks",
        "max_score": 100.0,
        "weight": 1.1,
        "source": "Google",
    },
    {
        "name": "ARC-Challenge",
        "category": "reasoning",
        "description": "AI2 Reasoning Challenge – science questions",
        "max_score": 100.0,
        "weight": 0.9,
        "source": "AI2",
    },
    {
        "name": "IFEval",
        "category": "instruction",
        "description": "Instruction Following Evaluation",
        "max_score": 100.0,
        "weight": 1.0,
        "source": "Google",
    },
    {
        "name": "Arena Elo",
        "category": "human_preference",
        "description": "Chatbot Arena Elo – human preference votes",
        "max_score": 1400.0,
        "weight": 1.5,
        "source": "LMSYS / Chatbot Arena",
    },
    {
        "name": "LiveBench",
        "category": "reasoning",
        "description": "Live benchmark – contamination-free reasoning",
        "max_score": 100.0,
        "weight": 1.2,
        "source": "LiveBench.ai",
    },
    {
        "name": "EQBench",
        "category": "emotional_intelligence",
        "description": "Emotional intelligence and nuance understanding",
        "max_score": 100.0,
        "weight": 0.8,
        "source": "EQ-Bench",
    },
]


MODELS_DATA = [
    # --- OpenAI ---
    {
        "name": "o3-mini-high",
        "provider": "OpenAI",
        "description": "OpenAI's efficient reasoning model with high compute",
        "parameters": "~100B (MoE)",
        "architecture": "Transformer (MoE) + CoT",
        "license_type": "Proprietary",
        "release_date": "2025-01-31",
        "cost_per_1m_input_tokens": 1.10,
        "cost_per_1m_output_tokens": 4.40,
        "avg_latency_ms": 4200,
        "context_window": 200000,
        "scores": {
            "MMLU": 87.3,
            "MMLU-Pro": 78.2,
            "GPQA Diamond": 79.7,
            "GSM8K": 97.9,
            "MATH-500": 96.7,
            "HumanEval": 92.7,
            "LiveCodeBench": 72.4,
            "BigBench-Hard": 90.1,
            "ARC-Challenge": 96.8,
            "IFEval": 86.1,
            "Arena Elo": 1331,
            "LiveBench": 73.3,
            "EQBench": 81.2,
        },
    },
    {
        "name": "o1",
        "provider": "OpenAI",
        "description": "OpenAI's strongest reasoning model with extended chain-of-thought",
        "parameters": "~200B (MoE)",
        "architecture": "Transformer (MoE) + CoT",
        "license_type": "Proprietary",
        "release_date": "2024-12-17",
        "cost_per_1m_input_tokens": 15.00,
        "cost_per_1m_output_tokens": 60.00,
        "avg_latency_ms": 8500,
        "context_window": 200000,
        "scores": {
            "MMLU": 91.8,
            "MMLU-Pro": 80.3,
            "GPQA Diamond": 78.0,
            "GSM8K": 97.8,
            "MATH-500": 96.4,
            "HumanEval": 92.4,
            "LiveCodeBench": 68.9,
            "BigBench-Hard": 93.4,
            "ARC-Challenge": 97.2,
            "IFEval": 88.6,
            "Arena Elo": 1350,
            "LiveBench": 71.8,
            "EQBench": 82.5,
        },
    },
    {
        "name": "o1-mini",
        "provider": "OpenAI",
        "description": "Cost-effective reasoning model",
        "parameters": "~50B",
        "architecture": "Transformer + CoT",
        "license_type": "Proprietary",
        "release_date": "2024-09-12",
        "cost_per_1m_input_tokens": 1.10,
        "cost_per_1m_output_tokens": 4.40,
        "avg_latency_ms": 4500,
        "context_window": 128000,
        "scores": {
            "MMLU": 85.2,
            "MMLU-Pro": 72.1,
            "GPQA Diamond": 60.0,
            "GSM8K": 96.2,
            "MATH-500": 94.8,
            "HumanEval": 92.4,
            "LiveCodeBench": 63.5,
            "BigBench-Hard": 82.5,
            "ARC-Challenge": 94.6,
            "IFEval": 80.5,
            "Arena Elo": 1262,
            "LiveBench": 64.2,
            "EQBench": 72.1,
        },
    },
    {
        "name": "GPT-4o",
        "provider": "OpenAI",
        "description": "OpenAI's flagship multimodal model",
        "parameters": "~200B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2024-11-20",
        "cost_per_1m_input_tokens": 2.50,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 320,
        "context_window": 128000,
        "scores": {
            "MMLU": 88.7,
            "MMLU-Pro": 72.6,
            "GPQA Diamond": 53.6,
            "GSM8K": 95.8,
            "MATH-500": 76.6,
            "HumanEval": 90.2,
            "LiveCodeBench": 46.8,
            "BigBench-Hard": 87.1,
            "ARC-Challenge": 96.4,
            "IFEval": 84.5,
            "Arena Elo": 1286,
            "LiveBench": 58.9,
            "EQBench": 79.3,
        },
    },
    {
        "name": "GPT-4o Mini",
        "provider": "OpenAI",
        "description": "Affordable small model replacing GPT-3.5 Turbo",
        "parameters": "~8B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-07-18",
        "cost_per_1m_input_tokens": 0.15,
        "cost_per_1m_output_tokens": 0.60,
        "avg_latency_ms": 180,
        "context_window": 128000,
        "scores": {
            "MMLU": 82.0,
            "MMLU-Pro": 63.2,
            "GPQA Diamond": 40.2,
            "GSM8K": 87.0,
            "MATH-500": 70.2,
            "HumanEval": 87.2,
            "LiveCodeBench": 36.2,
            "BigBench-Hard": 78.5,
            "ARC-Challenge": 93.1,
            "IFEval": 79.3,
            "Arena Elo": 1219,
            "LiveBench": 48.3,
            "EQBench": 68.4,
        },
    },
    {
        "name": "GPT-4.5",
        "provider": "OpenAI",
        "description": "OpenAI's largest and most capable non-reasoning model",
        "parameters": "~400B+",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2025-02-27",
        "cost_per_1m_input_tokens": 75.00,
        "cost_per_1m_output_tokens": 150.00,
        "avg_latency_ms": 600,
        "context_window": 128000,
        "scores": {
            "MMLU": 90.2,
            "MMLU-Pro": 81.8,
            "GPQA Diamond": 65.0,
            "GSM8K": 96.4,
            "MATH-500": 82.3,
            "HumanEval": 91.6,
            "LiveCodeBench": 48.5,
            "BigBench-Hard": 91.2,
            "ARC-Challenge": 97.1,
            "IFEval": 90.3,
            "Arena Elo": 1351,
            "LiveBench": 62.4,
            "EQBench": 87.1,
        },
    },
    {
        "name": "o1-pro",
        "provider": "OpenAI",
        "description": "o1 with extended compute for highest accuracy",
        "parameters": "~200B (MoE)",
        "architecture": "Transformer (MoE) + CoT",
        "license_type": "Proprietary",
        "release_date": "2025-03-19",
        "cost_per_1m_input_tokens": 150.00,
        "cost_per_1m_output_tokens": 600.00,
        "avg_latency_ms": 25000,
        "context_window": 200000,
        "scores": {
            "MMLU": 92.5,
            "MMLU-Pro": 83.1,
            "GPQA Diamond": 83.5,
            "GSM8K": 98.2,
            "MATH-500": 97.8,
            "HumanEval": 93.1,
            "LiveCodeBench": 73.8,
            "BigBench-Hard": 94.6,
            "ARC-Challenge": 97.5,
            "IFEval": 89.2,
            "Arena Elo": 1374,
            "LiveBench": 75.6,
            "EQBench": 84.6,
        },
    },
    # --- Anthropic ---
    {
        "name": "Claude 3.7 Sonnet",
        "provider": "Anthropic",
        "description": "Anthropic's latest hybrid reasoning model",
        "parameters": "~175B",
        "architecture": "Transformer + Extended Thinking",
        "license_type": "Proprietary",
        "release_date": "2025-02-24",
        "cost_per_1m_input_tokens": 3.00,
        "cost_per_1m_output_tokens": 15.00,
        "avg_latency_ms": 400,
        "context_window": 200000,
        "scores": {
            "MMLU": 89.5,
            "MMLU-Pro": 79.8,
            "GPQA Diamond": 68.0,
            "GSM8K": 97.1,
            "MATH-500": 84.2,
            "HumanEval": 93.7,
            "LiveCodeBench": 64.2,
            "BigBench-Hard": 91.8,
            "ARC-Challenge": 97.0,
            "IFEval": 91.2,
            "Arena Elo": 1354,
            "LiveBench": 68.5,
            "EQBench": 85.8,
        },
    },
    {
        "name": "Claude 3.5 Sonnet",
        "provider": "Anthropic",
        "description": "Best balance of performance and speed",
        "parameters": "~175B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-10-22",
        "cost_per_1m_input_tokens": 3.00,
        "cost_per_1m_output_tokens": 15.00,
        "avg_latency_ms": 350,
        "context_window": 200000,
        "scores": {
            "MMLU": 88.7,
            "MMLU-Pro": 78.0,
            "GPQA Diamond": 65.0,
            "GSM8K": 96.4,
            "MATH-500": 78.3,
            "HumanEval": 93.7,
            "LiveCodeBench": 55.8,
            "BigBench-Hard": 89.2,
            "ARC-Challenge": 96.7,
            "IFEval": 90.1,
            "Arena Elo": 1286,
            "LiveBench": 58.8,
            "EQBench": 83.1,
        },
    },
    {
        "name": "Claude 3.5 Haiku",
        "provider": "Anthropic",
        "description": "Fast and affordable Anthropic model",
        "parameters": "~70B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-10-22",
        "cost_per_1m_input_tokens": 0.80,
        "cost_per_1m_output_tokens": 4.00,
        "avg_latency_ms": 200,
        "context_window": 200000,
        "scores": {
            "MMLU": 84.2,
            "MMLU-Pro": 65.1,
            "GPQA Diamond": 41.5,
            "GSM8K": 90.5,
            "MATH-500": 69.2,
            "HumanEval": 88.1,
            "LiveCodeBench": 38.1,
            "BigBench-Hard": 79.8,
            "ARC-Challenge": 93.8,
            "IFEval": 81.2,
            "Arena Elo": 1213,
            "LiveBench": 47.6,
            "EQBench": 71.5,
        },
    },
    {
        "name": "Claude 3 Opus",
        "provider": "Anthropic",
        "description": "Anthropic's previous top-tier model",
        "parameters": "~175B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-02-29",
        "cost_per_1m_input_tokens": 15.00,
        "cost_per_1m_output_tokens": 75.00,
        "avg_latency_ms": 550,
        "context_window": 200000,
        "scores": {
            "MMLU": 86.8,
            "MMLU-Pro": 71.5,
            "GPQA Diamond": 50.4,
            "GSM8K": 95.0,
            "MATH-500": 60.1,
            "HumanEval": 84.9,
            "LiveCodeBench": 35.6,
            "BigBench-Hard": 86.8,
            "ARC-Challenge": 96.4,
            "IFEval": 85.3,
            "Arena Elo": 1233,
            "LiveBench": 49.1,
            "EQBench": 80.5,
        },
    },
    # --- Google ---
    {
        "name": "Gemini 2.5 Pro",
        "provider": "Google",
        "description": "Google's most capable thinking model with hybrid reasoning",
        "parameters": "~300B+ (MoE)",
        "architecture": "Transformer (MoE) + Thinking",
        "license_type": "Proprietary",
        "release_date": "2025-03-25",
        "cost_per_1m_input_tokens": 1.25,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 3500,
        "context_window": 1000000,
        "scores": {
            "MMLU": 91.5,
            "MMLU-Pro": 83.7,
            "GPQA Diamond": 84.0,
            "GSM8K": 98.0,
            "MATH-500": 97.2,
            "HumanEval": 93.5,
            "LiveCodeBench": 75.1,
            "BigBench-Hard": 94.8,
            "ARC-Challenge": 97.6,
            "IFEval": 91.8,
            "Arena Elo": 1399,
            "LiveBench": 78.2,
            "EQBench": 86.2,
        },
    },
    {
        "name": "Gemini 2.5 Flash",
        "provider": "Google",
        "description": "Google's fast thinking model for speed-sensitive tasks",
        "parameters": "~100B (MoE)",
        "architecture": "Transformer (MoE) + Thinking",
        "license_type": "Proprietary",
        "release_date": "2025-04-17",
        "cost_per_1m_input_tokens": 0.15,
        "cost_per_1m_output_tokens": 0.60,
        "avg_latency_ms": 900,
        "context_window": 1000000,
        "scores": {
            "MMLU": 89.8,
            "MMLU-Pro": 79.2,
            "GPQA Diamond": 70.5,
            "GSM8K": 96.5,
            "MATH-500": 91.8,
            "HumanEval": 91.4,
            "LiveCodeBench": 62.4,
            "BigBench-Hard": 88.9,
            "ARC-Challenge": 96.3,
            "IFEval": 88.5,
            "Arena Elo": 1363,
            "LiveBench": 70.1,
            "EQBench": 81.0,
        },
    },
    {
        "name": "Gemini 2.0 Flash",
        "provider": "Google",
        "description": "Google's fast and capable multimodal model",
        "parameters": "~100B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2025-02-05",
        "cost_per_1m_input_tokens": 0.10,
        "cost_per_1m_output_tokens": 0.40,
        "avg_latency_ms": 150,
        "context_window": 1000000,
        "scores": {
            "MMLU": 86.5,
            "MMLU-Pro": 73.8,
            "GPQA Diamond": 58.7,
            "GSM8K": 93.2,
            "MATH-500": 80.1,
            "HumanEval": 89.5,
            "LiveCodeBench": 44.9,
            "BigBench-Hard": 86.3,
            "ARC-Challenge": 95.3,
            "IFEval": 85.2,
            "Arena Elo": 1301,
            "LiveBench": 57.2,
            "EQBench": 76.8,
        },
    },
    {
        "name": "Gemini 2.0 Flash Lite",
        "provider": "Google",
        "description": "Cheapest Gemini model for high-volume tasks",
        "parameters": "~30B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2025-02-05",
        "cost_per_1m_input_tokens": 0.04,
        "cost_per_1m_output_tokens": 0.15,
        "avg_latency_ms": 100,
        "context_window": 1000000,
        "scores": {
            "MMLU": 80.1,
            "MMLU-Pro": 60.2,
            "GPQA Diamond": 35.6,
            "GSM8K": 85.2,
            "MATH-500": 62.3,
            "HumanEval": 78.5,
            "LiveCodeBench": 28.5,
            "BigBench-Hard": 72.1,
            "ARC-Challenge": 90.8,
            "IFEval": 75.1,
            "Arena Elo": 1170,
            "LiveBench": 38.5,
            "EQBench": 60.2,
        },
    },
    {
        "name": "Gemini 2.0 Pro",
        "provider": "Google",
        "description": "Strong reasoning and coding model",
        "parameters": "~300B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2025-02-24",
        "cost_per_1m_input_tokens": 2.50,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 500,
        "context_window": 2000000,
        "scores": {
            "MMLU": 90.2,
            "MMLU-Pro": 79.1,
            "GPQA Diamond": 68.3,
            "GSM8K": 96.8,
            "MATH-500": 86.4,
            "HumanEval": 91.8,
            "LiveCodeBench": 50.5,
            "BigBench-Hard": 91.5,
            "ARC-Challenge": 97.0,
            "IFEval": 89.4,
            "Arena Elo": 1322,
            "LiveBench": 63.8,
            "EQBench": 82.4,
        },
    },
    {
        "name": "Gemini 1.5 Pro",
        "provider": "Google",
        "description": "Previous-gen model with massive context window",
        "parameters": "~200B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2024-09-24",
        "cost_per_1m_input_tokens": 1.25,
        "cost_per_1m_output_tokens": 5.00,
        "avg_latency_ms": 400,
        "context_window": 2000000,
        "scores": {
            "MMLU": 85.9,
            "MMLU-Pro": 69.4,
            "GPQA Diamond": 46.2,
            "GSM8K": 91.4,
            "MATH-500": 67.5,
            "HumanEval": 84.1,
            "LiveCodeBench": 35.2,
            "BigBench-Hard": 84.0,
            "ARC-Challenge": 94.5,
            "IFEval": 83.7,
            "Arena Elo": 1262,
            "LiveBench": 51.1,
            "EQBench": 75.0,
        },
    },
    # --- DeepSeek ---
    {
        "name": "DeepSeek-R1",
        "provider": "DeepSeek",
        "description": "Open-source reasoning model rivaling o1",
        "parameters": "671B (MoE, 37B active)",
        "architecture": "Transformer (MoE) + RL",
        "license_type": "MIT",
        "release_date": "2025-01-20",
        "cost_per_1m_input_tokens": 0.55,
        "cost_per_1m_output_tokens": 2.19,
        "avg_latency_ms": 5200,
        "context_window": 128000,
        "scores": {
            "MMLU": 90.8,
            "MMLU-Pro": 79.8,
            "GPQA Diamond": 71.5,
            "GSM8K": 97.3,
            "MATH-500": 97.3,
            "HumanEval": 85.7,
            "LiveCodeBench": 65.9,
            "BigBench-Hard": 92.6,
            "ARC-Challenge": 96.8,
            "IFEval": 85.4,
            "Arena Elo": 1356,
            "LiveBench": 71.6,
            "EQBench": 80.3,
        },
    },
    {
        "name": "DeepSeek-V3",
        "provider": "DeepSeek",
        "description": "Cost-efficient MoE model competitive with GPT-4o",
        "parameters": "671B (MoE, 37B active)",
        "architecture": "Transformer (MoE)",
        "license_type": "DeepSeek",
        "release_date": "2024-12-26",
        "cost_per_1m_input_tokens": 0.27,
        "cost_per_1m_output_tokens": 1.10,
        "avg_latency_ms": 280,
        "context_window": 128000,
        "scores": {
            "MMLU": 88.5,
            "MMLU-Pro": 75.9,
            "GPQA Diamond": 59.1,
            "GSM8K": 96.7,
            "MATH-500": 90.2,
            "HumanEval": 88.4,
            "LiveCodeBench": 50.2,
            "BigBench-Hard": 87.8,
            "ARC-Challenge": 95.9,
            "IFEval": 86.6,
            "Arena Elo": 1318,
            "LiveBench": 61.8,
            "EQBench": 78.2,
        },
    },
    {
        "name": "DeepSeek-R1-Distill-Llama-70B",
        "provider": "DeepSeek",
        "description": "Distilled R1 into Llama 70B for faster inference",
        "parameters": "70B",
        "architecture": "Transformer",
        "license_type": "MIT",
        "release_date": "2025-01-20",
        "cost_per_1m_input_tokens": 0.40,
        "cost_per_1m_output_tokens": 0.80,
        "avg_latency_ms": 800,
        "context_window": 128000,
        "scores": {
            "MMLU": 83.5,
            "MMLU-Pro": 68.1,
            "GPQA Diamond": 50.8,
            "GSM8K": 94.5,
            "MATH-500": 89.4,
            "HumanEval": 80.5,
            "LiveCodeBench": 48.2,
            "BigBench-Hard": 82.4,
            "ARC-Challenge": 93.2,
            "IFEval": 78.3,
            "Arena Elo": 1258,
            "LiveBench": 55.8,
            "EQBench": 69.5,
        },
    },
    {
        "name": "DeepSeek-R1-Distill-Qwen-32B",
        "provider": "DeepSeek",
        "description": "Distilled R1 into Qwen 32B",
        "parameters": "32B",
        "architecture": "Transformer",
        "license_type": "MIT",
        "release_date": "2025-01-20",
        "cost_per_1m_input_tokens": 0.20,
        "cost_per_1m_output_tokens": 0.50,
        "avg_latency_ms": 500,
        "context_window": 128000,
        "scores": {
            "MMLU": 81.2,
            "MMLU-Pro": 65.3,
            "GPQA Diamond": 48.5,
            "GSM8K": 93.8,
            "MATH-500": 87.6,
            "HumanEval": 78.2,
            "LiveCodeBench": 45.1,
            "BigBench-Hard": 80.1,
            "ARC-Challenge": 91.8,
            "IFEval": 76.5,
            "Arena Elo": 1243,
            "LiveBench": 52.4,
            "EQBench": 66.8,
        },
    },
    # --- Meta ---
    {
        "name": "Llama 4 Maverick",
        "provider": "Meta",
        "description": "Meta's latest MoE flagship model",
        "parameters": "400B (MoE, 17B active)",
        "architecture": "Transformer (MoE)",
        "license_type": "Llama 4 Community",
        "release_date": "2025-04-05",
        "cost_per_1m_input_tokens": 0.25,
        "cost_per_1m_output_tokens": 0.98,
        "avg_latency_ms": 300,
        "context_window": 1000000,
        "scores": {
            "MMLU": 89.2,
            "MMLU-Pro": 78.5,
            "GPQA Diamond": 62.5,
            "GSM8K": 95.8,
            "MATH-500": 82.1,
            "HumanEval": 92.5,
            "LiveCodeBench": 51.2,
            "BigBench-Hard": 88.3,
            "ARC-Challenge": 96.5,
            "IFEval": 88.7,
            "Arena Elo": 1345,
            "LiveBench": 64.2,
            "EQBench": 79.8,
        },
    },
    {
        "name": "Llama 4 Scout",
        "provider": "Meta",
        "description": "Efficient model with 10M context window",
        "parameters": "109B (MoE, 17B active)",
        "architecture": "Transformer (MoE)",
        "license_type": "Llama 4 Community",
        "release_date": "2025-04-05",
        "cost_per_1m_input_tokens": 0.15,
        "cost_per_1m_output_tokens": 0.55,
        "avg_latency_ms": 200,
        "context_window": 10000000,
        "scores": {
            "MMLU": 84.8,
            "MMLU-Pro": 70.2,
            "GPQA Diamond": 48.5,
            "GSM8K": 93.2,
            "MATH-500": 74.5,
            "HumanEval": 88.2,
            "LiveCodeBench": 38.8,
            "BigBench-Hard": 82.5,
            "ARC-Challenge": 94.2,
            "IFEval": 83.5,
            "Arena Elo": 1270,
            "LiveBench": 52.8,
            "EQBench": 72.5,
        },
    },
    {
        "name": "Llama 3.3 70B",
        "provider": "Meta",
        "description": "Latest Llama 3 series 70B instruct model",
        "parameters": "70B",
        "architecture": "Transformer",
        "license_type": "Llama 3.3 Community",
        "release_date": "2024-12-06",
        "cost_per_1m_input_tokens": 0.10,
        "cost_per_1m_output_tokens": 0.25,
        "avg_latency_ms": 350,
        "context_window": 128000,
        "scores": {
            "MMLU": 86.0,
            "MMLU-Pro": 70.4,
            "GPQA Diamond": 46.7,
            "GSM8K": 95.1,
            "MATH-500": 77.1,
            "HumanEval": 85.2,
            "LiveCodeBench": 39.5,
            "BigBench-Hard": 85.5,
            "ARC-Challenge": 95.5,
            "IFEval": 87.1,
            "Arena Elo": 1264,
            "LiveBench": 55.1,
            "EQBench": 73.2,
        },
    },
    {
        "name": "Llama 3.1 405B",
        "provider": "Meta",
        "description": "Meta's largest open-source dense model",
        "parameters": "405B",
        "architecture": "Transformer",
        "license_type": "Llama 3.1 Community",
        "release_date": "2024-07-23",
        "cost_per_1m_input_tokens": 3.00,
        "cost_per_1m_output_tokens": 3.00,
        "avg_latency_ms": 600,
        "context_window": 128000,
        "scores": {
            "MMLU": 87.3,
            "MMLU-Pro": 73.3,
            "GPQA Diamond": 50.7,
            "GSM8K": 96.8,
            "MATH-500": 73.8,
            "HumanEval": 89.0,
            "LiveCodeBench": 39.8,
            "BigBench-Hard": 86.0,
            "ARC-Challenge": 96.1,
            "IFEval": 86.4,
            "Arena Elo": 1250,
            "LiveBench": 51.8,
            "EQBench": 77.2,
        },
    },
    {
        "name": "Llama 3.1 70B",
        "provider": "Meta",
        "description": "Strong open-source 70B model",
        "parameters": "70B",
        "architecture": "Transformer",
        "license_type": "Llama 3.1 Community",
        "release_date": "2024-07-23",
        "cost_per_1m_input_tokens": 0.10,
        "cost_per_1m_output_tokens": 0.25,
        "avg_latency_ms": 380,
        "context_window": 128000,
        "scores": {
            "MMLU": 83.6,
            "MMLU-Pro": 66.4,
            "GPQA Diamond": 46.7,
            "GSM8K": 93.0,
            "MATH-500": 68.0,
            "HumanEval": 80.5,
            "LiveCodeBench": 30.5,
            "BigBench-Hard": 81.2,
            "ARC-Challenge": 94.8,
            "IFEval": 83.6,
            "Arena Elo": 1199,
            "LiveBench": 46.3,
            "EQBench": 70.1,
        },
    },
    # --- xAI ---
    {
        "name": "Grok-3",
        "provider": "xAI",
        "description": "xAI's most powerful model with massive compute training",
        "parameters": "~600B+ (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2025-02-17",
        "cost_per_1m_input_tokens": 3.00,
        "cost_per_1m_output_tokens": 15.00,
        "avg_latency_ms": 450,
        "context_window": 131072,
        "scores": {
            "MMLU": 91.2,
            "MMLU-Pro": 81.3,
            "GPQA Diamond": 68.2,
            "GSM8K": 97.5,
            "MATH-500": 93.8,
            "HumanEval": 93.2,
            "LiveCodeBench": 68.5,
            "BigBench-Hard": 93.1,
            "ARC-Challenge": 97.2,
            "IFEval": 89.5,
            "Arena Elo": 1370,
            "LiveBench": 74.8,
            "EQBench": 84.1,
        },
    },
    {
        "name": "Grok-3 Mini",
        "provider": "xAI",
        "description": "xAI's fast reasoning model with configurable thinking",
        "parameters": "~100B (MoE)",
        "architecture": "Transformer (MoE) + Thinking",
        "license_type": "Proprietary",
        "release_date": "2025-02-17",
        "cost_per_1m_input_tokens": 0.30,
        "cost_per_1m_output_tokens": 0.50,
        "avg_latency_ms": 800,
        "context_window": 131072,
        "scores": {
            "MMLU": 86.8,
            "MMLU-Pro": 74.5,
            "GPQA Diamond": 55.8,
            "GSM8K": 95.8,
            "MATH-500": 89.2,
            "HumanEval": 90.5,
            "LiveCodeBench": 55.2,
            "BigBench-Hard": 86.5,
            "ARC-Challenge": 95.5,
            "IFEval": 85.8,
            "Arena Elo": 1307,
            "LiveBench": 63.1,
            "EQBench": 76.2,
        },
    },
    {
        "name": "Grok-2",
        "provider": "xAI",
        "description": "xAI's previous frontier model",
        "parameters": "~300B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2024-08-13",
        "cost_per_1m_input_tokens": 2.00,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 450,
        "context_window": 131072,
        "scores": {
            "MMLU": 87.5,
            "MMLU-Pro": 72.8,
            "GPQA Diamond": 56.4,
            "GSM8K": 94.1,
            "MATH-500": 76.1,
            "HumanEval": 88.4,
            "LiveCodeBench": 40.2,
            "BigBench-Hard": 85.7,
            "ARC-Challenge": 95.5,
            "IFEval": 83.7,
            "Arena Elo": 1262,
            "LiveBench": 53.8,
            "EQBench": 77.3,
        },
    },
    # --- Mistral AI ---
    {
        "name": "Mistral Large 2",
        "provider": "Mistral AI",
        "description": "Mistral's flagship with strong multilingual capabilities",
        "parameters": "123B",
        "architecture": "Transformer",
        "license_type": "Mistral Research",
        "release_date": "2024-11-18",
        "cost_per_1m_input_tokens": 2.00,
        "cost_per_1m_output_tokens": 6.00,
        "avg_latency_ms": 420,
        "context_window": 128000,
        "scores": {
            "MMLU": 84.0,
            "MMLU-Pro": 69.4,
            "GPQA Diamond": 49.0,
            "GSM8K": 92.7,
            "MATH-500": 71.3,
            "HumanEval": 84.1,
            "LiveCodeBench": 37.8,
            "BigBench-Hard": 82.8,
            "ARC-Challenge": 94.0,
            "IFEval": 82.3,
            "Arena Elo": 1241,
            "LiveBench": 50.8,
            "EQBench": 74.5,
        },
    },
    {
        "name": "Mistral Small 3",
        "provider": "Mistral AI",
        "description": "Compact and fast model for everyday tasks",
        "parameters": "24B",
        "architecture": "Transformer",
        "license_type": "Apache 2.0",
        "release_date": "2025-01-30",
        "cost_per_1m_input_tokens": 0.10,
        "cost_per_1m_output_tokens": 0.30,
        "avg_latency_ms": 150,
        "context_window": 32768,
        "scores": {
            "MMLU": 79.5,
            "MMLU-Pro": 60.8,
            "GPQA Diamond": 35.2,
            "GSM8K": 88.2,
            "MATH-500": 62.5,
            "HumanEval": 80.2,
            "LiveCodeBench": 28.4,
            "BigBench-Hard": 73.5,
            "ARC-Challenge": 91.2,
            "IFEval": 77.6,
            "Arena Elo": 1182,
            "LiveBench": 40.2,
            "EQBench": 63.8,
        },
    },
    # --- Alibaba / Qwen ---
    {
        "name": "Qwen 2.5 72B",
        "provider": "Alibaba",
        "description": "Strong multilingual model with excellent coding",
        "parameters": "72B",
        "architecture": "Transformer",
        "license_type": "Qwen",
        "release_date": "2024-09-19",
        "cost_per_1m_input_tokens": 0.15,
        "cost_per_1m_output_tokens": 0.40,
        "avg_latency_ms": 350,
        "context_window": 131072,
        "scores": {
            "MMLU": 85.3,
            "MMLU-Pro": 71.1,
            "GPQA Diamond": 49.0,
            "GSM8K": 91.6,
            "MATH-500": 83.1,
            "HumanEval": 86.6,
            "LiveCodeBench": 41.8,
            "BigBench-Hard": 84.6,
            "ARC-Challenge": 95.0,
            "IFEval": 83.8,
            "Arena Elo": 1249,
            "LiveBench": 52.5,
            "EQBench": 72.8,
        },
    },
    {
        "name": "QwQ-32B",
        "provider": "Alibaba",
        "description": "Qwen reasoning model competitive with o1-mini",
        "parameters": "32B",
        "architecture": "Transformer + CoT",
        "license_type": "Apache 2.0",
        "release_date": "2025-03-06",
        "cost_per_1m_input_tokens": 0.12,
        "cost_per_1m_output_tokens": 0.30,
        "avg_latency_ms": 1200,
        "context_window": 131072,
        "scores": {
            "MMLU": 84.5,
            "MMLU-Pro": 73.2,
            "GPQA Diamond": 59.5,
            "GSM8K": 95.5,
            "MATH-500": 93.2,
            "HumanEval": 86.4,
            "LiveCodeBench": 53.5,
            "BigBench-Hard": 85.8,
            "ARC-Challenge": 94.8,
            "IFEval": 82.5,
            "Arena Elo": 1316,
            "LiveBench": 64.8,
            "EQBench": 74.2,
        },
    },
    {
        "name": "Qwen 2.5 Coder 32B",
        "provider": "Alibaba",
        "description": "Specialized coding model from Qwen",
        "parameters": "32B",
        "architecture": "Transformer",
        "license_type": "Apache 2.0",
        "release_date": "2024-11-11",
        "cost_per_1m_input_tokens": 0.10,
        "cost_per_1m_output_tokens": 0.25,
        "avg_latency_ms": 280,
        "context_window": 131072,
        "scores": {
            "MMLU": 74.2,
            "MMLU-Pro": 56.8,
            "GPQA Diamond": 32.1,
            "GSM8K": 84.5,
            "MATH-500": 68.2,
            "HumanEval": 92.7,
            "LiveCodeBench": 55.8,
            "BigBench-Hard": 71.2,
            "ARC-Challenge": 88.5,
            "IFEval": 71.5,
            "Arena Elo": 1202,
            "LiveBench": 43.8,
            "EQBench": 58.5,
        },
    },
    # --- Cohere ---
    {
        "name": "Command R+",
        "provider": "Cohere",
        "description": "Enterprise-grade RAG-optimized model",
        "parameters": "104B",
        "architecture": "Transformer",
        "license_type": "CC-BY-NC",
        "release_date": "2024-08-01",
        "cost_per_1m_input_tokens": 2.50,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 400,
        "context_window": 128000,
        "scores": {
            "MMLU": 75.7,
            "MMLU-Pro": 58.2,
            "GPQA Diamond": 33.6,
            "GSM8K": 78.3,
            "MATH-500": 49.2,
            "HumanEval": 75.0,
            "LiveCodeBench": 22.1,
            "BigBench-Hard": 72.0,
            "ARC-Challenge": 87.8,
            "IFEval": 74.4,
            "Arena Elo": 1158,
            "LiveBench": 35.2,
            "EQBench": 62.4,
        },
    },
    {
        "name": "Command A",
        "provider": "Cohere",
        "description": "Cohere's latest high-performance enterprise model",
        "parameters": "111B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "CC-BY-NC",
        "release_date": "2025-03-13",
        "cost_per_1m_input_tokens": 2.50,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 350,
        "context_window": 256000,
        "scores": {
            "MMLU": 82.5,
            "MMLU-Pro": 66.8,
            "GPQA Diamond": 44.2,
            "GSM8K": 91.8,
            "MATH-500": 72.5,
            "HumanEval": 84.8,
            "LiveCodeBench": 35.5,
            "BigBench-Hard": 80.5,
            "ARC-Challenge": 92.5,
            "IFEval": 84.2,
            "Arena Elo": 1222,
            "LiveBench": 47.8,
            "EQBench": 71.5,
        },
    },
    # --- Amazon ---
    {
        "name": "Amazon Nova Pro",
        "provider": "Amazon",
        "description": "Amazon's capable multimodal model",
        "parameters": "~40B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-12-03",
        "cost_per_1m_input_tokens": 0.80,
        "cost_per_1m_output_tokens": 3.20,
        "avg_latency_ms": 300,
        "context_window": 300000,
        "scores": {
            "MMLU": 78.5,
            "MMLU-Pro": 61.2,
            "GPQA Diamond": 38.5,
            "GSM8K": 86.5,
            "MATH-500": 62.8,
            "HumanEval": 79.8,
            "LiveCodeBench": 30.5,
            "BigBench-Hard": 75.2,
            "ARC-Challenge": 91.5,
            "IFEval": 78.5,
            "Arena Elo": 1180,
            "LiveBench": 40.1,
            "EQBench": 64.5,
        },
    },
    {
        "name": "Amazon Nova Lite",
        "provider": "Amazon",
        "description": "Fast, budget-friendly Amazon model",
        "parameters": "~10B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-12-03",
        "cost_per_1m_input_tokens": 0.06,
        "cost_per_1m_output_tokens": 0.24,
        "avg_latency_ms": 120,
        "context_window": 300000,
        "scores": {
            "MMLU": 72.5,
            "MMLU-Pro": 51.5,
            "GPQA Diamond": 28.2,
            "GSM8K": 78.5,
            "MATH-500": 48.5,
            "HumanEval": 70.2,
            "LiveCodeBench": 18.5,
            "BigBench-Hard": 62.8,
            "ARC-Challenge": 86.5,
            "IFEval": 70.1,
            "Arena Elo": 1120,
            "LiveBench": 30.2,
            "EQBench": 52.1,
        },
    },
    # --- Microsoft ---
    {
        "name": "Phi-4",
        "provider": "Microsoft",
        "description": "Small but mighty 14B model with strong reasoning",
        "parameters": "14B",
        "architecture": "Transformer",
        "license_type": "MIT",
        "release_date": "2024-12-12",
        "cost_per_1m_input_tokens": 0.07,
        "cost_per_1m_output_tokens": 0.14,
        "avg_latency_ms": 150,
        "context_window": 16384,
        "scores": {
            "MMLU": 84.8,
            "MMLU-Pro": 70.4,
            "GPQA Diamond": 47.8,
            "GSM8K": 94.5,
            "MATH-500": 80.4,
            "HumanEval": 82.6,
            "LiveCodeBench": 38.5,
            "BigBench-Hard": 82.8,
            "ARC-Challenge": 95.1,
            "IFEval": 76.3,
            "Arena Elo": 1215,
            "LiveBench": 46.5,
            "EQBench": 70.2,
        },
    },
    # --- NVIDIA ---
    {
        "name": "Nemotron 70B",
        "provider": "NVIDIA",
        "description": "NVIDIA's Llama-based post-trained model",
        "parameters": "70B",
        "architecture": "Transformer",
        "license_type": "Llama 3.1 Community",
        "release_date": "2024-10-15",
        "cost_per_1m_input_tokens": 0.10,
        "cost_per_1m_output_tokens": 0.25,
        "avg_latency_ms": 380,
        "context_window": 128000,
        "scores": {
            "MMLU": 85.3,
            "MMLU-Pro": 68.9,
            "GPQA Diamond": 48.1,
            "GSM8K": 93.8,
            "MATH-500": 72.5,
            "HumanEval": 83.8,
            "LiveCodeBench": 35.8,
            "BigBench-Hard": 84.2,
            "ARC-Challenge": 95.2,
            "IFEval": 88.9,
            "Arena Elo": 1256,
            "LiveBench": 52.5,
            "EQBench": 73.8,
        },
    },
    # --- Perplexity ---
    {
        "name": "Sonar Pro",
        "provider": "Perplexity",
        "description": "Perplexity's best search-enhanced model",
        "parameters": "~70B",
        "architecture": "Transformer + Search",
        "license_type": "Proprietary",
        "release_date": "2025-02-01",
        "cost_per_1m_input_tokens": 3.00,
        "cost_per_1m_output_tokens": 15.00,
        "avg_latency_ms": 800,
        "context_window": 200000,
        "scores": {
            "MMLU": 82.5,
            "MMLU-Pro": 66.2,
            "GPQA Diamond": 42.5,
            "GSM8K": 90.2,
            "MATH-500": 68.5,
            "HumanEval": 80.5,
            "LiveCodeBench": 32.5,
            "BigBench-Hard": 78.5,
            "ARC-Challenge": 92.5,
            "IFEval": 81.2,
            "Arena Elo": 1218,
            "LiveBench": 45.5,
            "EQBench": 70.2,
        },
    },
    {
        "name": "Sonar",
        "provider": "Perplexity",
        "description": "Lightweight search-enhanced model",
        "parameters": "~8B",
        "architecture": "Transformer + Search",
        "license_type": "Proprietary",
        "release_date": "2025-02-01",
        "cost_per_1m_input_tokens": 1.00,
        "cost_per_1m_output_tokens": 1.00,
        "avg_latency_ms": 400,
        "context_window": 128000,
        "scores": {
            "MMLU": 75.2,
            "MMLU-Pro": 55.5,
            "GPQA Diamond": 30.5,
            "GSM8K": 82.5,
            "MATH-500": 55.2,
            "HumanEval": 72.5,
            "LiveCodeBench": 22.5,
            "BigBench-Hard": 68.5,
            "ARC-Challenge": 88.5,
            "IFEval": 73.5,
            "Arena Elo": 1145,
            "LiveBench": 33.5,
            "EQBench": 58.5,
        },
    },
    # --- Other Notable Models ---
    {
        "name": "Gemma 2 27B",
        "provider": "Google",
        "description": "Google's open-source Gemma 2 model",
        "parameters": "27B",
        "architecture": "Transformer",
        "license_type": "Gemma License",
        "release_date": "2024-06-27",
        "cost_per_1m_input_tokens": 0.07,
        "cost_per_1m_output_tokens": 0.14,
        "avg_latency_ms": 200,
        "context_window": 8192,
        "scores": {
            "MMLU": 75.2,
            "MMLU-Pro": 54.8,
            "GPQA Diamond": 28.5,
            "GSM8K": 79.8,
            "MATH-500": 45.8,
            "HumanEval": 71.5,
            "LiveCodeBench": 18.2,
            "BigBench-Hard": 70.2,
            "ARC-Challenge": 89.2,
            "IFEval": 70.8,
            "Arena Elo": 1155,
            "LiveBench": 34.5,
            "EQBench": 60.5,
        },
    },
    {
        "name": "Yi-Lightning",
        "provider": "01.AI",
        "description": "Yi's cost-effective fast model",
        "parameters": "~50B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2024-10-28",
        "cost_per_1m_input_tokens": 0.10,
        "cost_per_1m_output_tokens": 0.10,
        "avg_latency_ms": 250,
        "context_window": 16384,
        "scores": {
            "MMLU": 81.5,
            "MMLU-Pro": 63.1,
            "GPQA Diamond": 38.5,
            "GSM8K": 88.2,
            "MATH-500": 68.5,
            "HumanEval": 82.5,
            "LiveCodeBench": 30.5,
            "BigBench-Hard": 76.8,
            "ARC-Challenge": 91.8,
            "IFEval": 78.5,
            "Arena Elo": 1207,
            "LiveBench": 44.5,
            "EQBench": 67.5,
        },
    },
    {
        "name": "Reka Core",
        "provider": "Reka AI",
        "description": "Reka's most capable multimodal model",
        "parameters": "~67B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-04-15",
        "cost_per_1m_input_tokens": 3.00,
        "cost_per_1m_output_tokens": 15.00,
        "avg_latency_ms": 500,
        "context_window": 128000,
        "scores": {
            "MMLU": 82.8,
            "MMLU-Pro": 64.5,
            "GPQA Diamond": 42.5,
            "GSM8K": 88.5,
            "MATH-500": 58.2,
            "HumanEval": 78.2,
            "LiveCodeBench": 25.8,
            "BigBench-Hard": 77.8,
            "ARC-Challenge": 92.5,
            "IFEval": 80.5,
            "Arena Elo": 1195,
            "LiveBench": 43.5,
            "EQBench": 72.5,
        },
    },
    {
        "name": "Jamba 1.5 Large",
        "provider": "AI21",
        "description": "AI21's SSM-Transformer hybrid model",
        "parameters": "398B (MoE, 94B active)",
        "architecture": "Mamba-Transformer (MoE)",
        "license_type": "Jamba License",
        "release_date": "2024-08-22",
        "cost_per_1m_input_tokens": 2.00,
        "cost_per_1m_output_tokens": 8.00,
        "avg_latency_ms": 350,
        "context_window": 256000,
        "scores": {
            "MMLU": 80.0,
            "MMLU-Pro": 62.5,
            "GPQA Diamond": 38.8,
            "GSM8K": 87.5,
            "MATH-500": 55.8,
            "HumanEval": 79.5,
            "LiveCodeBench": 28.5,
            "BigBench-Hard": 76.2,
            "ARC-Challenge": 91.2,
            "IFEval": 79.5,
            "Arena Elo": 1185,
            "LiveBench": 41.8,
            "EQBench": 68.5,
        },
    },
    {
        "name": "MiniMax-01",
        "provider": "MiniMax",
        "description": "MiniMax's lightning-attention model with 4M context",
        "parameters": "456B (MoE, 46B active)",
        "architecture": "Transformer (MoE) + Lightning Attention",
        "license_type": "MiniMax-01",
        "release_date": "2025-01-15",
        "cost_per_1m_input_tokens": 0.20,
        "cost_per_1m_output_tokens": 1.10,
        "avg_latency_ms": 400,
        "context_window": 4000000,
        "scores": {
            "MMLU": 81.5,
            "MMLU-Pro": 65.8,
            "GPQA Diamond": 40.5,
            "GSM8K": 89.5,
            "MATH-500": 72.5,
            "HumanEval": 82.5,
            "LiveCodeBench": 32.5,
            "BigBench-Hard": 79.2,
            "ARC-Challenge": 92.8,
            "IFEval": 79.8,
            "Arena Elo": 1205,
            "LiveBench": 46.5,
            "EQBench": 68.5,
        },
    },
    {
        "name": "WizardLM 2 8x22B",
        "provider": "Microsoft",
        "description": "Microsoft's MoE instruction-tuned model",
        "parameters": "8x22B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Apache 2.0",
        "release_date": "2024-04-15",
        "cost_per_1m_input_tokens": 0.50,
        "cost_per_1m_output_tokens": 0.50,
        "avg_latency_ms": 350,
        "context_window": 65536,
        "scores": {
            "MMLU": 81.2,
            "MMLU-Pro": 60.5,
            "GPQA Diamond": 35.2,
            "GSM8K": 86.5,
            "MATH-500": 55.2,
            "HumanEval": 80.8,
            "LiveCodeBench": 25.8,
            "BigBench-Hard": 77.5,
            "ARC-Challenge": 91.5,
            "IFEval": 79.8,
            "Arena Elo": 1175,
            "LiveBench": 40.5,
            "EQBench": 68.2,
        },
    },
]


def seed_database(db: Session):
    """Seed the database with benchmarks and 50 top LLM models."""
    existing = db.query(Model).first()
    if existing:
        return

    # Create benchmarks
    benchmark_objs = {}
    for b_data in BENCHMARKS:
        benchmark = Benchmark(**b_data)
        db.add(benchmark)
        db.flush()
        benchmark_objs[b_data["name"]] = benchmark

    # Create models and scores
    for m_data in MODELS_DATA:
        scores_data = m_data.pop("scores")
        model = Model(**m_data)
        db.add(model)
        db.flush()

        score_list = []
        for bench_name, raw_score in scores_data.items():
            benchmark = benchmark_objs.get(bench_name)
            if not benchmark:
                continue
            normalized = normalize_score(raw_score, benchmark.max_score)
            score = BenchmarkScore(
                model_id=model.id,
                benchmark_id=benchmark.id,
                raw_score=raw_score,
                normalized_score=normalized,
                language="en",
                evaluation_date=model.release_date,
            )
            db.add(score)
            score_list.append(
                {
                    "benchmark_name": bench_name,
                    "normalized_score": normalized,
                }
            )

        overall, confidence = compute_weighted_overall_score(
            score_list, DEFAULT_WEIGHTS
        )
        model.overall_score = overall
        model.confidence = confidence

    db.commit()
