"""
Seed data for BenchIndex – realistic LLM benchmark scores.
Populates the database with ~15 models and 12 benchmarks.
"""

from sqlalchemy.orm import Session
from models import Model, Benchmark, BenchmarkScore
from normalization import (
    normalize_score,
    compute_weighted_overall_score,
    DEFAULT_WEIGHTS,
)


BENCHMARKS = [
    {
        "name": "MMLU",
        "category": "knowledge",
        "description": "Massive Multitask Language Understanding – 57 subjects",
        "max_score": 100.0,
        "weight": 1.2,
        "source": "HuggingFace Open LLM Leaderboard",
    },
    {
        "name": "MMLU-Pro",
        "category": "knowledge",
        "description": "MMLU Professional – harder, more discriminative version",
        "max_score": 100.0,
        "weight": 1.3,
        "source": "TIGER-Lab",
    },
    {
        "name": "GSM8K",
        "category": "math",
        "description": "Grade School Math – 8.5K multi-step math problems",
        "max_score": 100.0,
        "weight": 1.0,
        "source": "OpenAI",
    },
    {
        "name": "MATH",
        "category": "math",
        "description": "Competition-level math – algebra, geometry, number theory",
        "max_score": 100.0,
        "weight": 1.1,
        "source": "Hendrycks et al.",
    },
    {
        "name": "HumanEval",
        "category": "coding",
        "description": "Python coding problems – functional correctness",
        "max_score": 100.0,
        "weight": 1.2,
        "source": "OpenAI",
    },
    {
        "name": "MBPP",
        "category": "coding",
        "description": "Mostly Basic Python Programming – 974 tasks",
        "max_score": 100.0,
        "weight": 1.0,
        "source": "Google Research",
    },
    {
        "name": "BigBench-Hard",
        "category": "reasoning",
        "description": "23 challenging BIG-Bench tasks beyond human average",
        "max_score": 100.0,
        "weight": 1.1,
        "source": "Google/BIG-Bench",
    },
    {
        "name": "ARC-Challenge",
        "category": "reasoning",
        "description": "AI2 Reasoning Challenge – grade-school science questions",
        "max_score": 100.0,
        "weight": 0.9,
        "source": "AI2",
    },
    {
        "name": "HellaSwag",
        "category": "reasoning",
        "description": "Commonsense reasoning – sentence completion",
        "max_score": 100.0,
        "weight": 0.8,
        "source": "Zellers et al.",
    },
    {
        "name": "TruthfulQA",
        "category": "safety",
        "description": "Measures truthfulness – avoidance of common misconceptions",
        "max_score": 100.0,
        "weight": 1.0,
        "source": "Lin et al.",
    },
    {
        "name": "GPQA",
        "category": "knowledge",
        "description": "Graduate-level science QA – PhD-level questions",
        "max_score": 100.0,
        "weight": 1.3,
        "source": "NYU",
    },
    {
        "name": "IFEval",
        "category": "instruction",
        "description": "Instruction Following Evaluation – precise instruction adherence",
        "max_score": 100.0,
        "weight": 1.0,
        "source": "Google",
    },
]


MODELS_DATA = [
    {
        "name": "GPT-4o",
        "provider": "OpenAI",
        "description": "OpenAI's flagship multimodal model with optimized speed and cost",
        "parameters": "~200B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2024-05-13",
        "cost_per_1m_input_tokens": 2.50,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 320,
        "context_window": 128000,
        "scores": {
            "MMLU": 88.7,
            "MMLU-Pro": 72.6,
            "GSM8K": 95.8,
            "MATH": 76.6,
            "HumanEval": 90.2,
            "MBPP": 87.8,
            "BigBench-Hard": 87.1,
            "ARC-Challenge": 96.4,
            "HellaSwag": 95.3,
            "TruthfulQA": 64.2,
            "GPQA": 53.6,
            "IFEval": 84.5,
        },
    },
    {
        "name": "GPT-4o-mini",
        "provider": "OpenAI",
        "description": "Affordable small model from OpenAI, replacing GPT-3.5 Turbo",
        "parameters": "~8B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-07-18",
        "cost_per_1m_input_tokens": 0.15,
        "cost_per_1m_output_tokens": 0.60,
        "avg_latency_ms": 180,
        "context_window": 128000,
        "scores": {
            "MMLU": 82.0,
            "MMLU-Pro": 63.2,
            "GSM8K": 87.0,
            "MATH": 70.2,
            "HumanEval": 87.2,
            "MBPP": 85.7,
            "BigBench-Hard": 78.5,
            "ARC-Challenge": 93.1,
            "HellaSwag": 92.7,
            "TruthfulQA": 59.8,
            "GPQA": 40.2,
            "IFEval": 79.3,
        },
    },
    {
        "name": "o1",
        "provider": "OpenAI",
        "description": "OpenAI reasoning model with extended chain-of-thought",
        "parameters": "~200B (MoE)",
        "architecture": "Transformer (MoE) + CoT",
        "license_type": "Proprietary",
        "release_date": "2024-12-17",
        "cost_per_1m_input_tokens": 15.00,
        "cost_per_1m_output_tokens": 60.00,
        "avg_latency_ms": 8500,
        "context_window": 200000,
        "scores": {
            "MMLU": 91.8,
            "MMLU-Pro": 80.3,
            "GSM8K": 97.8,
            "MATH": 96.4,
            "HumanEval": 92.4,
            "MBPP": 89.5,
            "BigBench-Hard": 93.4,
            "ARC-Challenge": 97.2,
            "HellaSwag": 96.1,
            "TruthfulQA": 68.4,
            "GPQA": 78.0,
            "IFEval": 88.6,
        },
    },
    {
        "name": "Claude 3.5 Sonnet",
        "provider": "Anthropic",
        "description": "Anthropic's best balance of performance and speed",
        "parameters": "~175B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-10-22",
        "cost_per_1m_input_tokens": 3.00,
        "cost_per_1m_output_tokens": 15.00,
        "avg_latency_ms": 350,
        "context_window": 200000,
        "scores": {
            "MMLU": 88.7,
            "MMLU-Pro": 78.0,
            "GSM8K": 96.4,
            "MATH": 78.3,
            "HumanEval": 93.7,
            "MBPP": 91.0,
            "BigBench-Hard": 89.2,
            "ARC-Challenge": 96.7,
            "HellaSwag": 95.8,
            "TruthfulQA": 66.7,
            "GPQA": 65.0,
            "IFEval": 90.1,
        },
    },
    {
        "name": "Claude 3.5 Haiku",
        "provider": "Anthropic",
        "description": "Fastest Anthropic model, good price-performance ratio",
        "parameters": "~70B",
        "architecture": "Transformer",
        "license_type": "Proprietary",
        "release_date": "2024-10-22",
        "cost_per_1m_input_tokens": 0.80,
        "cost_per_1m_output_tokens": 4.00,
        "avg_latency_ms": 200,
        "context_window": 200000,
        "scores": {
            "MMLU": 84.2,
            "MMLU-Pro": 65.1,
            "GSM8K": 90.5,
            "MATH": 69.2,
            "HumanEval": 88.1,
            "MBPP": 85.3,
            "BigBench-Hard": 79.8,
            "ARC-Challenge": 93.8,
            "HellaSwag": 93.5,
            "TruthfulQA": 60.1,
            "GPQA": 41.5,
            "IFEval": 81.2,
        },
    },
    {
        "name": "Gemini 2.0 Flash",
        "provider": "Google",
        "description": "Google's fast and capable multimodal model",
        "parameters": "~100B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2025-02-05",
        "cost_per_1m_input_tokens": 0.10,
        "cost_per_1m_output_tokens": 0.40,
        "avg_latency_ms": 150,
        "context_window": 1000000,
        "scores": {
            "MMLU": 86.5,
            "MMLU-Pro": 73.8,
            "GSM8K": 93.2,
            "MATH": 80.1,
            "HumanEval": 89.5,
            "MBPP": 88.4,
            "BigBench-Hard": 86.3,
            "ARC-Challenge": 95.3,
            "HellaSwag": 94.0,
            "TruthfulQA": 62.3,
            "GPQA": 58.7,
            "IFEval": 85.2,
        },
    },
    {
        "name": "Gemini 2.0 Pro",
        "provider": "Google",
        "description": "Google's most capable reasoning model",
        "parameters": "~300B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2025-02-24",
        "cost_per_1m_input_tokens": 2.50,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 500,
        "context_window": 2000000,
        "scores": {
            "MMLU": 90.2,
            "MMLU-Pro": 79.1,
            "GSM8K": 96.8,
            "MATH": 86.4,
            "HumanEval": 91.8,
            "MBPP": 90.3,
            "BigBench-Hard": 91.5,
            "ARC-Challenge": 97.0,
            "HellaSwag": 96.4,
            "TruthfulQA": 66.1,
            "GPQA": 68.3,
            "IFEval": 89.4,
        },
    },
    {
        "name": "Llama 3.1 405B",
        "provider": "Meta",
        "description": "Meta's largest open-source model, competitive with GPT-4",
        "parameters": "405B",
        "architecture": "Transformer",
        "license_type": "Llama 3.1 Community",
        "release_date": "2024-07-23",
        "cost_per_1m_input_tokens": 3.00,
        "cost_per_1m_output_tokens": 3.00,
        "avg_latency_ms": 600,
        "context_window": 128000,
        "scores": {
            "MMLU": 87.3,
            "MMLU-Pro": 73.3,
            "GSM8K": 96.8,
            "MATH": 73.8,
            "HumanEval": 89.0,
            "MBPP": 88.6,
            "BigBench-Hard": 86.0,
            "ARC-Challenge": 96.1,
            "HellaSwag": 95.2,
            "TruthfulQA": 52.3,
            "GPQA": 50.7,
            "IFEval": 86.4,
        },
    },
    {
        "name": "Llama 3.1 70B",
        "provider": "Meta",
        "description": "Strong open-source model, great balance of size and performance",
        "parameters": "70B",
        "architecture": "Transformer",
        "license_type": "Llama 3.1 Community",
        "release_date": "2024-07-23",
        "cost_per_1m_input_tokens": 0.88,
        "cost_per_1m_output_tokens": 0.88,
        "avg_latency_ms": 380,
        "context_window": 128000,
        "scores": {
            "MMLU": 83.6,
            "MMLU-Pro": 66.4,
            "GSM8K": 93.0,
            "MATH": 68.0,
            "HumanEval": 80.5,
            "MBPP": 82.0,
            "BigBench-Hard": 81.2,
            "ARC-Challenge": 94.8,
            "HellaSwag": 94.5,
            "TruthfulQA": 53.8,
            "GPQA": 46.7,
            "IFEval": 83.6,
        },
    },
    {
        "name": "Mistral Large 2",
        "provider": "Mistral AI",
        "description": "Mistral's flagship model with strong multilingual capabilities",
        "parameters": "123B",
        "architecture": "Transformer",
        "license_type": "Mistral Research",
        "release_date": "2024-07-24",
        "cost_per_1m_input_tokens": 2.00,
        "cost_per_1m_output_tokens": 6.00,
        "avg_latency_ms": 420,
        "context_window": 128000,
        "scores": {
            "MMLU": 84.0,
            "MMLU-Pro": 69.4,
            "GSM8K": 92.7,
            "MATH": 71.3,
            "HumanEval": 84.1,
            "MBPP": 85.5,
            "BigBench-Hard": 82.8,
            "ARC-Challenge": 94.0,
            "HellaSwag": 93.2,
            "TruthfulQA": 55.4,
            "GPQA": 49.0,
            "IFEval": 82.3,
        },
    },
    {
        "name": "DeepSeek-V3",
        "provider": "DeepSeek",
        "description": "DeepSeek's MoE model with excellent cost efficiency",
        "parameters": "671B (MoE, 37B active)",
        "architecture": "Transformer (MoE)",
        "license_type": "DeepSeek",
        "release_date": "2024-12-26",
        "cost_per_1m_input_tokens": 0.27,
        "cost_per_1m_output_tokens": 1.10,
        "avg_latency_ms": 280,
        "context_window": 128000,
        "scores": {
            "MMLU": 87.1,
            "MMLU-Pro": 75.9,
            "GSM8K": 96.7,
            "MATH": 84.6,
            "HumanEval": 88.4,
            "MBPP": 87.0,
            "BigBench-Hard": 87.8,
            "ARC-Challenge": 95.9,
            "HellaSwag": 95.1,
            "TruthfulQA": 57.2,
            "GPQA": 59.1,
            "IFEval": 86.6,
        },
    },
    {
        "name": "DeepSeek-R1",
        "provider": "DeepSeek",
        "description": "DeepSeek reasoning model rivaling o1 at fraction of cost",
        "parameters": "671B (MoE, 37B active)",
        "architecture": "Transformer (MoE) + RL",
        "license_type": "MIT",
        "release_date": "2025-01-20",
        "cost_per_1m_input_tokens": 0.55,
        "cost_per_1m_output_tokens": 2.19,
        "avg_latency_ms": 5200,
        "context_window": 128000,
        "scores": {
            "MMLU": 90.8,
            "MMLU-Pro": 79.8,
            "GSM8K": 97.3,
            "MATH": 94.9,
            "HumanEval": 85.7,
            "MBPP": 84.2,
            "BigBench-Hard": 92.6,
            "ARC-Challenge": 96.8,
            "HellaSwag": 95.8,
            "TruthfulQA": 65.8,
            "GPQA": 71.5,
            "IFEval": 85.4,
        },
    },
    {
        "name": "Qwen 2.5 72B",
        "provider": "Alibaba",
        "description": "Alibaba's strong open-source model with multilingual focus",
        "parameters": "72B",
        "architecture": "Transformer",
        "license_type": "Qwen",
        "release_date": "2024-09-19",
        "cost_per_1m_input_tokens": 0.90,
        "cost_per_1m_output_tokens": 0.90,
        "avg_latency_ms": 350,
        "context_window": 131072,
        "scores": {
            "MMLU": 85.3,
            "MMLU-Pro": 71.1,
            "GSM8K": 91.6,
            "MATH": 83.1,
            "HumanEval": 86.6,
            "MBPP": 88.2,
            "BigBench-Hard": 84.6,
            "ARC-Challenge": 95.0,
            "HellaSwag": 94.0,
            "TruthfulQA": 56.7,
            "GPQA": 49.0,
            "IFEval": 83.8,
        },
    },
    {
        "name": "Grok-2",
        "provider": "xAI",
        "description": "xAI's frontier model with real-time data access",
        "parameters": "~300B (MoE)",
        "architecture": "Transformer (MoE)",
        "license_type": "Proprietary",
        "release_date": "2024-08-13",
        "cost_per_1m_input_tokens": 2.00,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 450,
        "context_window": 131072,
        "scores": {
            "MMLU": 87.5,
            "MMLU-Pro": 72.8,
            "GSM8K": 94.1,
            "MATH": 76.1,
            "HumanEval": 88.4,
            "MBPP": 86.2,
            "BigBench-Hard": 85.7,
            "ARC-Challenge": 95.5,
            "HellaSwag": 94.8,
            "TruthfulQA": 60.3,
            "GPQA": 56.4,
            "IFEval": 83.7,
        },
    },
    {
        "name": "Command R+",
        "provider": "Cohere",
        "description": "Cohere's enterprise-grade RAG-optimized model",
        "parameters": "104B",
        "architecture": "Transformer",
        "license_type": "CC-BY-NC",
        "release_date": "2024-04-04",
        "cost_per_1m_input_tokens": 2.50,
        "cost_per_1m_output_tokens": 10.00,
        "avg_latency_ms": 400,
        "context_window": 128000,
        "scores": {
            "MMLU": 75.7,
            "MMLU-Pro": 58.2,
            "GSM8K": 78.3,
            "MATH": 49.2,
            "HumanEval": 75.0,
            "MBPP": 72.3,
            "BigBench-Hard": 72.0,
            "ARC-Challenge": 87.8,
            "HellaSwag": 89.6,
            "TruthfulQA": 55.2,
            "GPQA": 33.6,
            "IFEval": 74.4,
        },
    },
]


def seed_database(db: Session):
    """Seed the database with benchmarks and model data."""
    # Check if already seeded
    existing = db.query(Model).first()
    if existing:
        return

    # Create benchmarks
    benchmark_objs = {}
    for b_data in BENCHMARKS:
        benchmark = Benchmark(**b_data)
        db.add(benchmark)
        db.flush()
        benchmark_objs[b_data["name"]] = benchmark

    # Create models and scores
    for m_data in MODELS_DATA:
        scores_data = m_data.pop("scores")
        model = Model(**m_data)
        db.add(model)
        db.flush()

        score_list = []
        for bench_name, raw_score in scores_data.items():
            benchmark = benchmark_objs[bench_name]
            normalized = normalize_score(raw_score, benchmark.max_score)
            score = BenchmarkScore(
                model_id=model.id,
                benchmark_id=benchmark.id,
                raw_score=raw_score,
                normalized_score=normalized,
                language="en",
                evaluation_date=model.release_date,
            )
            db.add(score)
            score_list.append(
                {
                    "benchmark_name": bench_name,
                    "normalized_score": normalized,
                }
            )

        # Compute overall score
        overall, confidence = compute_weighted_overall_score(
            score_list, DEFAULT_WEIGHTS
        )
        model.overall_score = overall
        model.confidence = confidence

    db.commit()
